web3:
  url: None
  pkey: None

pools:
  - address: '0x29bA3D899E8a819Cf920adAfF53ef1CF31969E66'
    start_height: 10940335
    type: uniswap
  - address: '0x4C34a687906092ec11CC04DDF30b71e29747Ed76'
    start_height: 10969116
    type: balancer

reward_start: 10940337
reward_per_block: 1.8
batch_size: 200

token:
  address: '0x27702a26126e0B3702af63Ee09aC4d1A084EF628'
  symbol: ALEPH

aleph:
  channel: 'TEST'
  api_server: 'https://api2.aleph.im'